### ISSUE TITLE
Hardware: Divide the GND into signal and power GND's

### ISSUE THREAD

**Issue by comesanha** [spacelab-ufsc/eps-re#11]
Talking together with Victor Noster, we defined the signal GND as the one represented with a "triangle", while the power GND is represented with the "dashes" in the figure below.

![Screenshot from 2023-09-06 15-23-06](https://github.com/spacelab-ufsc/eps-re/assets/4386446/b9bd1f1d-10e9-43bb-9fff-18bed5bb285c)

**Comment by rebeccaquintino** [comment]
The "triangle" was not placed for the resistive divider and the 4.7uF capacitor as shown in the datasheet image.
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/637a9c45-915e-4794-a798-25f948c4eb1e)
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/8eb1d055-afa1-4613-aafc-2673fce251e6)
