### ISSUE TITLE
Hardware: update some components' proximity 

### ISSUE THREAD

**Issue by comesanha** [spacelab-ufsc/eps-re#12]
You should try to:

- Move Q5 closer to the IC.
- Move C92 and C93 down, closer to the IC, without moving them away from the MOSFETs.
- Move C81 to the right, closer to the IC.
- Move C84 to the left, closer to the IC.
- Move C98 and C90 to the left and down, closer to the IC, without moving them away from the R<sub>sense</sub>.

![WhatsApp Image 2023-09-06 at 15 17 12](https://github.com/spacelab-ufsc/eps-re/assets/4386446/07bf1dd1-77dd-459e-9a86-29fa290fe5fe)

**Comment by rebeccaquintino** [comment]
- [x] Move Q5 closer to the IC.

![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/3da48650-72de-4834-a658-29d29c251fb1)

- [x] Move C92 and C93 down, closer to the IC without moving them away from the MOSFETs.
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/223fd806-92ae-4947-8e0a-388c8497505b)

- [x] Move C81 to the right, closer to the IC.
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/e98a4e1b-7b87-4079-8042-0a4dbc3f71c9)

- [x] Move C84 to the left and down, closer to the IC.
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/10bd94ca-a3b4-4969-adf2-eb8293a9df89)

- [X] Move C98 and C90 to the left and down, closer to the IC, without moving them away from the Rsense.
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/6da011a3-a8cc-48ca-88e0-60398aa61624)
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/70d4f56f-9392-4254-9fd8-779284685f77)
