### ISSUE TITLE
Hardware: Update components location

### ISSUE THREAD

**Issue by vitoria-b** [spacelab-ufsc/eps-re#15]
According to datasheet: "_Filter the VIN input to the LTC3833 with a simple RC filter close to the pin. The RC filter should be referenced to signal ground_".

In our layout, R31/C10, R32/C11, R96/C99 and R95/C99 are far from pin number 10 (their respective Vin). It would be better to put closer. Below are disposed referenced images:

**- Original typical application:**
![image](https://github.com/spacelab-ufsc/eps-re/assets/71644689/62a44a82-2065-4819-be7f-e215cf961055)

**- In our schematics:**
![image](https://github.com/spacelab-ufsc/eps-re/assets/71644689/1aab765c-a07e-40ec-9ac3-276432dcfc2f)

**- In layout:**
![image](https://github.com/spacelab-ufsc/eps-re/assets/71644689/e627e280-a86a-43f3-a377-118a1222ae61)

**Comment by rebeccaquintino** [comment]
- [X] R31/C10, R32/C11, R96/C99 and R95/C99 are close to the Pin.

![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/6dd788bf-1a47-4ebb-8b07-29d60e3e4e0c)
