### ISSUE TITLE
Hardware: Add the thermistor to the schematic

### ISSUE THREAD

**Issue by joaoclaudioeb** [spacelab-ufsc/eps-re#7]
The BQ24650RVAT needs a thermistor to properly adjust the V<sub>MP</sub> of the solar panel when the temperature varies. It is necessary to calculate its value and define its position in the PCB.

**Comment by joaoclaudioeb** [comment]
Update: We won't be using a thermistor for now. We're going to use a fixed value of resistors in the "resistive network", on the MPPSET pin. Because we still have to consider how, on the mission, we're going to add this thermistor to the satellite. So, for now, the "resistive network" should be calculated for a fixed value of 25°C.

**Comment by rebeccaquintino** [comment]
Update: We used the Texas Instruments spreadsheet to design the resistor network. We concluded that 270k Ohms is enough to conduct the RE²PS tests.

PS: It would be interesting to evaluate how to add the thermistor in the future.
