### ISSUE TITLE
Hardware: Add Kelvin connection for shunt resistor and update some components' proximity

### ISSUE THREAD

**Issue by comesanha** [spacelab-ufsc/eps-re#9]
From LTC3833 Datasheet:

- Place de sense resistor (R78/R79/R48/R47 in circuit) close to the inductor (L1/L2/L4/L8 - in circuit) on the output side.

- Use a Kelvin (4-wire) connection across the sense resistor (R78/R79/R48/R47 in circuit) and route the traces together as a differential pair. RC filter the differential sense signal close to SENSE+/SENSE– pins, placing the filter capacitor (C18-R43-R44/C19-R45-R46/C106-R64-R65/C107-R62-R61 in circuit) as close as possible to the pins. 

- Place the resistive feedback divider RFB1/2 (R53-R54/R55-R56/R49-R50/R51-R52/R80-R140/R81-R142) as close as possible to VOSNS+/VOSNS– pins and route the remote output and ground traces together as a differential pair and terminate as close to the regulation point as possible. (preferably Kelvin connect across the capacitor at the remote output point).

**Comment by vitoria-b** [comment]
From the datasheet: "_Place the ceramic CVCC capacitor as close as possible to INTVCC and PGND pins. Likewise, the CB capacitor should be as close as possible to BOOST and SW pins. These capacitors provide the gate charging currents for the power MOSFETs_" should our Cvcc: C110/C111/C22/C23 be closer to 11 and 12 pins or it is in an okay distance? 
![image](https://github.com/spacelab-ufsc/eps-re/assets/71644689/c44b115f-8c00-4f4b-b4cb-a9b588c13ea3)

**Comment by rebeccaquintino** [comment]
- [X] Place de sense resistor (R78/R79/R48/R47 in circuit) close to the inductor (L1/L2/L4/L8 - in circuit) on the output side.
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/1278f582-e6c0-4fe7-b341-7e822a886e35)

- [x] Use a Kelvin (4-wire) connection across the sense resistor (R78/R79/R48/R47 in circuit) and route the traces together as a differential pair. RC filter the differential sense signal close to SENSE+/SENSE– pins, placing the filter capacitor (C18-R43-R44/C19-R45-R46/C106-R64-R65/C107-R62-R61 in circuit) as close as possible to the pins.
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/c60e7d02-caef-4d8f-b5ff-dea1164f6666)
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/f1eb2ab8-4f4c-49d3-907c-194bbf294394)

- [X] Place the resistive feedback divider RFB1/2 (R53-R54/R55-R56/R49-R50/R51-R52/R80-R140/R81-R142) as close as possible to VOSNS+/VOSNS– pins and route the remote output and ground traces together as a differential pair and terminate as close to the regulation point as possible. (preferably Kelvin connect across the capacitor at the remote output point). 
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/57e9dc0d-3dd4-4764-9f29-a8f5b050affb)
![image](https://github.com/spacelab-ufsc/eps-re/assets/89544210/2e7bbab6-2164-4955-a205-76a0f6c8e0cd)
